import test from 'node:test';
import assert from 'node:assert/strict';
import {insightStory,reviewedMonth,scenarioAnnual,spendingEntries} from '../src/insight-story.js';
const month=(amount=2000)=>({income:10000,accounts:[{id:'bank',name:'Bank',opening:0,closing:10000}],cards:[],fixed:[],oneoffs:[{id:'food',name:'Meals',category:'Dining',amount,date:'2030-03-01'}],investments:[{id:'sip',name:'SIP',amount:1000}],assets:[],receipts:[],completed:[0,1,2,3,4,5,7],step:7});
function state(){return {users:[{id:'u',name:'User',recurring:{fixed:[],investments:[]}}],months:{u:{'2030-01':month(),'2030-02':month(),'2030-03':month()}}};}
test('finished reviewed months explain spending changes with exact evidence',()=>{const s=state();s.months.u['2030-03'].oneoffs[0].amount=4500;const r=insightStory(s,['u'],'2030-03','2030-04');assert.equal(r.ready,true);assert.equal(r.drivers[0].change,2500);assert.ok(r.cards.some(c=>c.category==='Dining'&&c.evidence.includes('2,500')));assert.ok(r.cards.some(c=>c.tone==='progress'));});
test('in-progress and incomplete months never claim a spending improvement',()=>{const s=state();s.months.u['2030-03'].oneoffs=[];for(const today of ['2030-03','2030-04']){if(today==='2030-04')s.months.u['2030-03'].completed=[];const r=insightStory(s,['u'],'2030-03',today);assert.equal(r.ready,false);assert.ok(r.drivers.every(d=>d.change===null));assert.ok(!r.cards.some(c=>c.title==='More breathing room this month'));}});
test('family comparisons require review by every member',()=>{const s=state();s.users.push({id:'v',name:'Other',recurring:{}});s.months.v={'2030-03':month()};assert.equal(reviewedMonth(s,['u','v'],'2030-03'),true);const r=insightStory(s,['u','v'],'2030-03','2030-04');assert.equal(r.previousReady,false);assert.ok(r.drivers.every(d=>d.change===null));s.months.v['2030-03'].completed=[];assert.equal(reviewedMonth(s,['u','v'],'2030-03'),false);});
test('baseline requires all three months and excludes unreviewed estimates',()=>{const s=state();assert.equal(insightStory(s,['u'],'2030-03','2030-04').baselineReady,false);s.months.u['2029-12']=month(8000);let r=insightStory(s,['u'],'2030-03','2030-04');assert.equal(r.drivers[0].average,4000);s.months.u['2030-03'].completed=[];s.months.u['2030-03'].fixed=[{id:'estimate',name:'Rent',amount:5000,estimated:true}];assert.equal(spendingEntries(s,['u'],'2030-03').length,1);});
test('refunds reduce driver totals and receipts do not inflate spending or income',()=>{const s=state();s.months.u['2030-03'].receipts=[{id:'refund',name:'Refund',type:'refund',refundPeriod:'current',category:'Dining',amount:500},{id:'loan',name:'Return',type:'loan_return',amount:50000}];const r=insightStory(s,['u'],'2030-03','2030-04');assert.equal(r.drivers[0].amount,1500);assert.equal(r.now.income,10000);assert.equal(r.entries.length,2);});
test('recurring warning uses active fixed defaults and separates contributions',()=>{const s=state();s.users[0].recurring={fixed:[{name:'Rent',amount:7000,start:'2030-01'},{name:'Expired',amount:10000,start:'2029-01',end:'2030-02'}],investments:[{name:'SIP',amount:1000,start:'2030-01'}]};const r=insightStory(s,['u'],'2030-03','2030-04');assert.equal(r.fixed,7000);assert.equal(r.investments,1000);assert.equal(r.commitmentRate,.7);assert.ok(r.cards.some(c=>c.target==='commitments'));});
test('carried values and changed asset coverage prevent wealth comparison',()=>{const s=state();assert.equal(insightStory(s,['u'],'2030-03','2030-04').wealthComparable,true);s.months.u['2030-03'].accounts[0].carried=true;assert.equal(insightStory(s,['u'],'2030-03','2030-04').wealthComparable,false);delete s.months.u['2030-03'].accounts[0].carried;s.months.u['2030-03'].assets=[{id:'new',value:5000}];assert.equal(insightStory(s,['u'],'2030-03','2030-04').wealthComparable,false);});
test('scenario uses simple twelve-month arithmetic and missing months interrupt habits',()=>{assert.equal(scenarioAnnual(2000),24000);assert.equal(scenarioAnnual(-50),0);const s=state();delete s.months.u['2030-02'];const r=insightStory(s,['u'],'2030-03','2030-04');assert.ok(!r.cards.some(c=>c.title==='You’re building a consistent buffer'));});
