import React,{useState,useId} from 'react';
import {MoneyArt} from './Visuals.jsx';
import {monthLabel} from './model.js';
import {categories,defaultBudget,presets,validBudget,monthlyData,delta,insight,streakInfo,budgetActual,budgetStatus} from './insights.js';
const money=v=>v===null?'Not entered':new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(v);
const percent=v=>v===null?'Not available':`${(v*100).toFixed(1)}%`;
export function Metrics({now,previous}){const text=insight(now,previous);return <>{text&&<p className="insight-line">{text}</p>}<section className="kpis metrics">{[['Income','income'],['Expenses','expense'],['Invested','invest'],['Uncommitted','remaining']].map(([label,key])=>{const d=delta(now[key],previous[key]);return <div className={`card metric-${key}`} key={key}><MoneyArt kind={key}/><small className="metric-label">{label}</small><h2>{money(now[key])}</h2>{['invest','remaining'].includes(key)&&<p>{percent(now[key==='invest'?'investRate':'uncommittedRate'])} of income</p>}{d!==null&&<small className="delta">{d===0?'No change':`${d>0?'↑':'↓'}${Math.abs(d*100).toFixed(1)}%`} vs last month</small>}</div>;})}</section><p className="muted">Invested is contributions made. Uncommitted is income minus expenses and investments. Review all spending sections to calculate uncommitted money.</p></>}
export function Streak({state,uid,month}){const result=streakInfo(state,uid,month),[dismissed,setDismissed]=useState('');return <div className="streak"><b>{result.count} {result.count===1?'month':'months'} tallied in a row</b><small>All eight steps completed and balances matched. The selected month can still be in progress.</small>{result.reset&&dismissed!==result.reset&&<p role="status">{result.reset} <button onClick={()=>setDismissed(result.reset)}>Dismiss</button></p>}</div>}
export function Trend({rows,bars=false}){
 const chartId=useId().replace(/:/g,'');
 const series=bars?[['Income','income','#4470ff','#8ba9ff'],['Expenses','expense','#d748da','#f6a4ed'],['Invested','invest','#9258e9','#dac0ff']]:[['Invested','investRate','#8957e5','#e6dbff'],['Uncommitted','uncommittedRate','#169b73','#b9f0e0']];
 if(!rows.some(r=>series.some(([,k])=>r[k]!==null)))return <p className="chart-empty">No data yet for this range</p>;
 const values=rows.flatMap(r=>series.flatMap(([,k])=>r[k]===null?[]:[r[k]])),min=Math.min(0,...values),peak=Math.max(bars?1:.01,...values),max=peak*1.15,y=v=>194-(v-min)/(max-min)*164,slot=470/Math.max(1,rows.length),x=i=>62+slot*(i+.5),barWidth=Math.min(22,slot/4.3);
 const format=v=>bars?new Intl.NumberFormat('en-IN',{notation:'compact',maximumFractionDigits:1}).format(v):`${(v*100).toFixed(0)}%`;
 return <div className="chart-block"><svg viewBox="0 0 560 235" className="chart polished-chart" role="img" aria-label={bars?'Income, expenses and investments in rupees':'Invested and uncommitted percentages'}><defs>{series.map(([,key,color,light])=><linearGradient key={key} id={`${chartId}-${key}`} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={light}/><stop offset="100%" stopColor={color}/></linearGradient>)}</defs>{Array.from({length:5},(_,i)=>min+(max-min)*i/4).map((v,i)=><g key={i}><line x1="62" x2="538" y1={y(v)} y2={y(v)} stroke="#e8eef9" strokeDasharray={i?'3 4':undefined}/><text x="53" y={y(v)+4} textAnchor="end" fontSize="10" fill="#64769c">{format(v)}</text></g>)}{series.map(([label,key,color],j)=><g key={key}>{rows.map((r,i)=>r[key]===null?null:<g key={r.key}><title>{monthLabel(r.key)}: {label} {bars?money(r[key]):percent(r[key])}</title>{bars?<rect x={x(i)+(j-1)*(barWidth+3)-barWidth/2} y={Math.min(y(0),y(r[key]))} width={barWidth} height={Math.max(1,Math.abs(y(0)-y(r[key])))} rx="4" fill={`url(#${chartId}-${key})`}/>:<>{i>0&&rows[i-1][key]!==null&&<><path d={`M ${x(i-1)} ${y(0)} L ${x(i-1)} ${y(rows[i-1][key])} L ${x(i)} ${y(r[key])} L ${x(i)} ${y(0)} Z`} fill={color} opacity=".07"/><line x1={x(i-1)} x2={x(i)} y1={y(rows[i-1][key])} y2={y(r[key])} stroke={color} strokeWidth="2.5"/></>}<circle cx={x(i)} cy={y(r[key])} r="4.5" fill={color} stroke="white" strokeWidth="1.5"/></>}</g>)}</g>)}{rows.map((r,i)=>i%Math.max(1,Math.ceil(rows.length/6))===0||i===rows.length-1?<text key={r.key} x={x(i)} y="217" textAnchor="middle" fontSize="10" fill="#64769c">{monthLabel(r.key,true)}</text>:null)}</svg><div className="trend-legend">{series.map(([label,key,color])=><span key={key}><i style={{background:color}}/>{label}</span>)}</div><p className="chart-caption">{bars?'Amounts in INR. Gaps mean no recorded data.':'Share of income. Gaps mean no recorded data or no positive income.'}</p></div>;
}
export function Detail({rows}){return <div className="table-scroll"><table><thead><tr>{['Month','Income','Expenses','Invested','Uncommitted','Invested %','Uncommitted %'].map(v=><th key={v}>{v}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.key}><td>{monthLabel(r.key,true)}</td>{['income','expense','invest','remaining'].map(k=><td key={k}>{money(r[k])}</td>)}<td>{percent(r.investRate)}</td><td>{percent(r.uncommittedRate)}</td></tr>)}</tbody></table></div>}
export function Budget({user,record,onSave}){
 const saved=validBudget(user.budget)?user.budget:defaultBudget(),[draft,setDraft]=useState(saved),[editing,setEditing]=useState(false),[error,setError]=useState('');const b=editing?draft:saved,values=budgetActual(record,b),income=Number(record?.income||0);
 const descriptions={Balanced:'50/30/20: a general starting point for everyday budgeting.','Debt payoff':'50/20/30: more room for building a buffer. Map debt payments deliberately; they are not investment contributions.','Aggressive saver':'35/15/50: a starting target for saving half your income.',Custom:'Choose three percentages that total 100.'};
 async function save(e){e.preventDefault();if(!validBudget(draft)){setError('Targets must be between 0 and 100 and total 100%.');return;}try{await onSave(draft);setEditing(false);setError('');}catch(e){setError(e.message);}}
 const savingsTarget=income*b.targets.Savings/100,progress=savingsTarget>0?Math.min(100,Math.max(0,values.Savings/savingsTarget*100)):0;
 return <section className="panel budget"><div className="goal-hero"><div><span className="goal-eyebrow">YOUR PLAN · {b.preset}</span><h2>Make room for what matters.</h2><p>Small, consistent steps build a stronger financial future.</p><p>{descriptions[b.preset]}</p></div><div className="goal-ring" style={{'--progress':`${progress}%`}} role="img" aria-label={income>0&&savingsTarget>0?`Savings goal ${progress.toFixed(0)}% reached`:'Add income and a savings target to track progress'}><div><strong>{income>0&&savingsTarget>0?`${progress.toFixed(0)}%`:'—'}</strong><small>of savings goal</small></div></div></div><div className="goal-message"><b>{income<=0?'Start with your income':savingsTarget<=0?'Choose a savings goal':values.Savings>=savingsTarget?'Your recorded savings have reached your target':`${money(Math.max(0,savingsTarget-values.Savings))} to your savings goal`}</b><p>{income<=0?'Add this month’s income in Monthly Check-in to turn your targets into a plan.':`Recorded savings: ${money(values.Savings)} · Monthly target: ${money(savingsTarget)}. Every contribution counts.`}</p><small>Progress reflects recorded entries for the selected month. Review all entries before closing the month.</small></div><h3>Your monthly targets</h3>{editing?<form onSubmit={save}><div className="fields"><label>Preset<select value={draft.preset} onChange={e=>{const preset=e.target.value,v=presets[preset];setDraft({...draft,preset,targets:v?{Needs:v[0],Wants:v[1],Savings:v[2]}:draft.targets});}}>{Object.keys(descriptions).map(p=><option key={p}>{p}</option>)}</select></label><div className="budget-inputs">{['Needs','Wants','Savings'].map(k=><label key={k}>{k} target (%)<input type="number" min="0" max="100" step="1" required value={draft.targets[k]} onChange={e=>setDraft({...draft,preset:'Custom',targets:{...draft.targets,[k]:e.target.value===''?'':Number(e.target.value)}})}/></label>)}</div><h4>Map your categories</h4>{Object.entries(categories).map(([g,label])=><label key={g}>{label}<select value={draft.mapping[g]} onChange={e=>setDraft({...draft,mapping:{...draft.mapping,[g]:e.target.value}})}>{['Needs','Wants','Savings'].map(k=><option key={k}>{k}</option>)}</select></label>)}</div>{error&&<p className="error" role="alert">{error}</p>}<div className="actions"><button type="button" onClick={()=>{setEditing(false);setError('');}}>Cancel</button><button className="primary">Save budget goals</button></div></form>:<button onClick={()=>{setDraft(saved);setEditing(true);}}>Edit targets and categories</button>}
 <div className="budget-meters">{['Needs','Wants','Savings'].map(k=>{const actual=income>0?values[k]/income*100:null,status=actual===null?'':budgetStatus(k,actual,b.targets[k]);return <div className={`goal-card goal-${k.toLowerCase()}`} key={k}><span className="goal-symbol" aria-hidden="true">{k==='Needs'?'⌂':k==='Wants'?'☆':'↗'}</span><h3>{k}</h3><p><b>{income>0?money(income*b.targets[k]/100):'Add income'}</b> monthly target</p><p><b>Recorded</b> {money(values[k])} · {actual===null?'Add income to see percentage':`${actual.toFixed(1)}%`} / target {b.targets[k]}%</p><div className={`meter ${status}`}><span style={{width:`${Math.max(0,Math.min(100,actual||0))}%`}}/><i style={{left:`${b.targets[k]}%`}}/></div><small>{actual===null?'No comparison yet':status==='good'?(k==='Savings'?'Target reached — keep building':'Within your planned limit'):status==='caution'?'Within 5 percentage points of target':'Outside target by more than 5 percentage points'}</small></div>;})}</div><p className="muted">Savings here means entries mapped to Savings; unspent cash is not counted. Credit-card bills are counted once as a category. General guideline, not personalized financial advice.</p></section>;
}
