import React,{useMemo,useRef,useState} from 'react';
import {insightStory,scenarioAnnual,spendingEntries} from './insight-story.js';
import {monthLabel} from './model.js';
import {Guidance} from './Guidance.jsx';
const money=n=>n==null?'—':new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n);
const signed=n=>n==null?'—':`${n>0?'+':n<0?'−':''}${money(Math.abs(n))}`;
const tones={context:['◈','Context'],progress:['↗','Progress'],caution:['!','Worth a look']};
export function InsightsPage({state,ids,month,onReview,onSettings}){
 const story=useMemo(()=>insightStory(state,ids,month),[state,ids.join('|'),month]);
 const [selected,setSelected]=useState(null),[category,setCategory]=useState(''),[reduction,setReduction]=useState(0);
 const spendingRef=useRef(null),commitmentsRef=useRef(null),rhythmRef=useRef(null);
 const options=story.drivers.filter(d=>d.amount>0),chosen=options.find(d=>d.category===category)||options[0],cap=chosen?Math.floor(chosen.amount):0,value=Math.min(cap,reduction);
 const focus=ref=>{ref.current?.scrollIntoView({behavior:'smooth',block:'start'});ref.current?.focus({preventScroll:true});};
 function action(card){if(card.category){setSelected(card.category);focus(spendingRef);}else if(card.target==='spending')focus(spendingRef);else if(card.target==='commitments')focus(commitmentsRef);else if(card.target==='rhythm')focus(rhythmRef);else onReview(card.step);}
 const visibleEntries=story.entries.filter(r=>r.category===selected);
 const previousEntries=story.previousReady?spendingEntries(state,ids,story.previousKey).filter(r=>r.category===selected):[];
 return <div className="insights-page">
  <section className="insights-intro"><div><p className="eyebrow">YOUR MONEY, WITH CONTEXT</p><h2>{monthLabel(month)} — the story behind your month.</h2><p>Understand the changes. Recognise the habits. Choose your next step.</p></div><span className={`insight-quality ${story.ready?'reviewed':''}`}>{story.ready?'Reviewed month':story.closed?'Review needed':'Month in progress'}</span></section>
  <section aria-label="Worth your attention" className="insight-cards">{story.cards.map(card=><article className={`insight-message tone-${card.tone}`} key={card.title}><div className="insight-tone"><span aria-hidden="true">{tones[card.tone][0]}</span>{tones[card.tone][1]}</div><h3>{card.title}</h3><p>{card.message}</p><div className="insight-evidence">{card.evidence}</div><button onClick={()=>action(card)}>{card.action} →</button></article>)}</section>
  <section className="panel insight-section" ref={spendingRef} tabIndex={-1}><div className="insight-section-head"><div><p className="eyebrow">FOLLOW THE CHANGE</p><h2>Where your spending moved</h2><p>{story.ready&&story.previousReady?`Compared with ${monthLabel(story.previousKey)}. Select a category to see the entries behind it.`:'Recorded spending so far. Comparisons wait until both months are finished and reviewed.'}</p></div><span className="badge">{story.entries.length} recorded entries</span></div>
   {story.drivers.length?<div className="insight-table-wrap"><table className="insight-table"><thead><tr><th>Category</th><th>This month</th><th>Change vs last month</th><th>Prior 3-month average</th></tr></thead><tbody>{story.drivers.map(d=><tr key={d.category} className={selected===d.category?'selected':''}><td><button aria-expanded={selected===d.category} onClick={()=>setSelected(selected===d.category?null:d.category)}>{d.category} <span aria-hidden="true">{selected===d.category?'−':'+'}</span></button></td><td>{money(d.amount)}</td><td>{signed(d.change)}</td><td>{money(d.average)}</td></tr>)}</tbody></table></div>:<div className="insight-empty"><h3>Your first entries will start the story.</h3><p>Add spending through Daily or Monthly Check-in, then return to explore it here.</p><button onClick={()=>onReview(5)}>Add an expense →</button></div>}
   {selected&&<div className="insight-drilldown"><h3>{selected} · {monthLabel(month,true)}</h3>{visibleEntries.length?<ul>{visibleEntries.map(r=><li key={r.uid+r.group+r.id}><div><b>{r.name}</b><small>{ids.length>1?r.owner+' · ':''}{r.date||monthLabel(month,true)}{r.group==='receipts'?' · Refund':''}</small></div><strong>{money(r.amount)}</strong></li>)}</ul>:<p>No entries in this category this month; its comparison comes from the prior month.</p>}{previousEntries.length>0&&<details className="insight-prior"><summary>View {monthLabel(story.previousKey,true)} entries</summary><ul>{previousEntries.map(r=><li key={r.uid+r.group+r.id}><div><b>{r.name}</b><small>{ids.length>1?r.owner+' · ':''}{r.date||monthLabel(story.previousKey,true)}</small></div><strong>{money(r.amount)}</strong></li>)}</ul></details>}<button onClick={()=>onReview(story.drivers.find(d=>d.category===selected)?.step||5)}>{ids.length>1?'Open my monthly entries':'Review monthly entries'} →</button></div>}
   <p className="insight-footnote">{story.baselineReady?`Baseline: ${monthLabel(story.baselineKeys[0],true)}–${monthLabel(story.baselineKeys[2],true)}.`:'The three-month baseline needs three consecutive reviewed, finished months.'} Refunds reduce the relevant recorded category; unreviewed recurring estimates are excluded.</p>
  </section>
  <div className="insight-pair"><section className="panel insight-section" ref={rhythmRef} tabIndex={-1}><div className="insight-section-head"><div><p className="eyebrow">CONSISTENCY OVER TIME</p><h2>Your financial rhythm</h2><p>Money left after expenses and investment contributions—not your bank balance.</p></div></div><div className="rhythm-strip">{story.rhythm.map(r=><div key={r.month} className={r.ready?(r.remaining>=0?'rhythm-positive':'rhythm-negative'):'rhythm-pending'}><span>{monthLabel(r.month,true)}</span><b aria-hidden="true">{r.ready?(r.remaining>=0?'↗':'↘'):'◌'}</b><strong>{r.ready?money(r.remaining):'Awaiting review'}</strong><small>{r.ready?'Reviewed cash flow':r.month===month?'Selected month':'Incomplete / missing'}</small></div>)}</div><p className="insight-footnote">A missing month interrupts a streak; it never counts as zero spending.</p></section>
  <section className="panel insight-section" ref={commitmentsRef} tabIndex={-1}><div className="insight-section-head"><div><p className="eyebrow">BEFORE FLEXIBLE SPENDING</p><h2>Your recurring commitments</h2><p>Configured defaults active in {monthLabel(month,true)}. Actual monthly amounts can differ.</p></div></div><div className="commitment-summary"><div><small>Fixed expenses</small><strong>{money(story.fixed)}</strong><span>{story.commitmentRate===null?'Review income to see its share':`${(story.commitmentRate*100).toFixed(0)}% of reviewed income`}</span></div><div><small>Planned contributions</small><strong>{money(story.investments)}</strong><span>Shown separately from expenses</span></div></div>{story.commitments.length?<ul className="commitment-list">{story.commitments.slice(0,5).map((r,i)=><li key={i}><div><b>{r.name}</b><small>{ids.length>1?r.owner+' · ':''}{r.group==='investments'?'Investment contribution':'Fixed expense'}{r.end?' · Ends '+monthLabel(r.end,true):''}</small></div><strong>{money(r.amount)}</strong></li>)}</ul>:<p className="insight-empty">No recurring defaults are active for this month.</p>}{story.commitments.length>5&&<p className="insight-footnote">Showing the five largest of {story.commitments.length} commitments.</p>}<button onClick={onSettings}>Manage my recurring settings →</button></section></div>
  <div className="insight-pair"><section className="panel insight-section"><div className="insight-section-head"><div><p className="eyebrow">THE BIGGER PICTURE</p><h2>What moved your wealth?</h2><p>Changes in tracked balances compared with {monthLabel(story.previousKey,true)}.</p></div></div>{story.wealthComparable?<ul className="wealth-movers">{story.wealthMoves.slice(0,5).map((r,i)=><li key={i}><div><b>{r.name}</b>{ids.length>1&&<small>{r.owner}</small>}</div><strong>{signed(r.change)}</strong></li>)}</ul>:<div className="insight-empty"><p>Confirm both months’ balances for the same holdings to see a fair comparison. Carried values stay out of this calculation.</p><button onClick={()=>onReview(1)}>Review my balances →</button></div>}<Guidance compact items={[{title:'Balance movement, not investment return',text:'Changes can include deposits, withdrawals and market movements. Liabilities are not deducted.'}]}/></section>
  <section className="panel insight-section scenario"><div className="insight-section-head"><div><p className="eyebrow">EXPLORE A POSSIBILITY</p><h2>Make a little more room.</h2><p>Try a spending reduction and see its simple annual equivalent.</p></div></div>{story.ready&&options.length?<><label>Spending category<select value={chosen?.category||''} onChange={e=>{setCategory(e.target.value);setReduction(0);}}>{options.map(d=><option key={d.category}>{d.category}</option>)}</select></label><label>Reduce by {money(value)} per month<input type="range" aria-label="Monthly spending reduction" min="0" max={cap} step="1" value={value} onChange={e=>setReduction(Number(e.target.value))}/></label><div className="scenario-result"><strong>{money(scenarioAnnual(value))}</strong><span>potentially freed over 12 months</span></div><p className="insight-footnote">Based on {money(chosen?.amount)} recorded in {monthLabel(month,true)}. This is an illustrative reduction × 12, not a forecast or investment-return estimate.</p></>:<div className="insight-empty"><p>Choose a finished, reviewed month with spending to explore a realistic starting amount.</p></div>}</section></div>
 </div>;
}
