import React,{useState,useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {GROUPS,STEPS,id,currentMonth,validMonth,shiftMonth,monthLabel,monthFor,ensureMonth,updateMonth,totals,aggregate,dateRange,familyFor,talliedStreak} from './model.js';
import './styles.css';
import {PageIcon} from './Visuals.jsx';
import {Metrics,Streak,Trend,Detail,Budget} from './DashboardExtras.jsx';
import {monthlyData} from './insights.js';
import {request,useServerState} from './api.js';
import {parseLegacyWorkbook} from './legacy-xlsx.js';
const INR=new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2});
const money=n=>n===null?'Not entered':INR.format(n);const pct=n=>`${(n*100).toFixed(1)}%`;
const NAV=['Dashboard','Monthly Check-in','Expenses & Investments','Budget Goals','Reconciliation','Trends & Insights','Family','Settings'];
function Panel({title,children}){return <section className="panel"><h3 className="panel-heading"><span className="panel-icon"><PageIcon name={title}/></span>{title}</h3>{children}</section>}
function Field({label,...props}){return <label>{label}<input {...props}/></label>}
function Modal({title,onClose,children}){const ref=useRef(null);useEffect(()=>{const old=document.activeElement;ref.current.showModal();ref.current.querySelector("input,textarea,select")?.focus();return()=>old?.focus();},[]);return <dialog ref={ref} aria-label={title} onCancel={e=>{e.preventDefault();onClose();}} onClick={e=>{if(e.target===e.currentTarget)onClose();}}><div className="dialog-head"><h2>{title}</h2><button type="button" aria-label="Close dialog" onClick={onClose}>×</button></div>{children}</dialog>}
function Editor({spec,onClose,onSave}){const [values,setValues]=useState(spec.initial||{}),[error,setError]=useState('');function change(k,v){setValues(x=>({...x,[k]:v}));setError('');}return <Modal title={spec.title} onClose={onClose}><form onSubmit={async e=>{e.preventDefault();try{await onSave(values);}catch(err){setError(err.message);}}}><div className="fields">{spec.description&&<p className="muted">{spec.description}</p>}{spec.fields.map(f=><label key={f.key}>{f.label}{f.type==='file'?<input autoFocus={f===spec.fields[0]} type="file" accept={f.accept} required={f.required!==false} onChange={e=>change(f.key,e.target.files?.[0]||null)}/>:f.type==='checkbox'?<input type="checkbox" checked={!!values[f.key]} onChange={e=>change(f.key,e.target.checked)}/>:f.type==='select'?<select required={f.required!==false} value={values[f.key]??''} onChange={e=>change(f.key,e.target.value)}>{f.options.map(o=><option key={o} value={o}>{o}</option>)}</select>:f.type==='textarea'?<textarea required={f.required!==false} maxLength={2000} value={values[f.key]??''} onInput={e=>change(f.key,e.target.value)} onChange={e=>change(f.key,e.target.value)}/>:<input autoFocus={f===spec.fields[0]} type={f.type||'text'} required={f.required!==false} min={f.min} max={f.max} step={f.step} maxLength={f.type==='text'||!f.type?100:undefined} value={values[f.key]??''} onInput={e=>change(f.key,e.target.value)} onChange={e=>change(f.key,e.target.value)}/>}</label>)}</div>{error&&<p role="alert" className="error">{error}</p>}<div className="actions"><button type="button" onClick={onClose}>Cancel</button><button className="primary" type="submit">{spec.saveLabel||'Save'}</button></div></form></Modal>}
const nameField={key:'name',label:'Name'};const amountField={key:'amount',label:'Amount (₹)',type:'number',min:0,step:'0.01'};
function App({initialState}){
 const {state,update:setState,busy,error:storageError,retry,exportDraft,familyAction}=useServerState(initialState);
 const [page,setPage]=useState('Dashboard'),[month,setMonth]=useState(currentMonth()),[view,setView]=useState('individual'),[editor,setEditor]=useState(null),[notice,setNotice]=useState(''),[invitation,setInvitation]=useState(null);
 const uid=state?.activeUserId;useEffect(()=>{if(uid)setState(s=>ensureMonth(s,uid,month));},[uid,month]);
 const user=state.users.find(u=>u.id===uid),family=familyFor(state,uid),familyView=view==='family'&&!!family,ids=familyView?family.memberIds:[uid],m=monthFor(state,uid,month),current=aggregate(ids.map(i=>monthFor(state,i,month))),range=dateRange(state,ids);
 const hasStarted=Object.values(state.months[uid]||{}).some(record=>Number(record.income||0)!==0||['accounts','cards','fixed','investments','oneoffs','remarks'].some(group=>record[group]?.length)||(record.completed?.length||0)>0),showDashboardData=familyView||hasStarted;
 const chartKeys=Array.from({length:6},(_,i)=>shiftMonth(month,i-5)).filter(k=>k>=range.first),rows=chartKeys.map(key=>monthlyData(state,ids,key)),now=monthlyData(state,ids,month),previous=monthlyData(state,ids,shiftMonth(month,-1));
 async function commit(fn,message='Saved'){const saved=await setState(fn);if(saved)setNotice(message);return saved;}
 function edit(spec,save){setEditor({...spec,save});}
 function mutate(fn,message){commit(s=>updateMonth(s,uid,month,fn),message);}
 function confirmDelete(title,save,description='This removes the item from this month. Other months are kept.'){edit({title,description,fields:[],saveLabel:'Delete'},save);}
 function editRecord(group,item){const recurring=['accounts','cards','fixed','investments'].includes(group),repeatable=group==='fixed';const fields=group==='remarks'?[{key:'text',label:'Remark',type:'textarea'}]:[nameField,...(group==='accounts'?[{key:'opening',label:'Opening balance (₹)',type:'number',step:'0.01'},{key:'closing',label:'Closing balance (₹)',type:'number',step:'0.01',required:false}]:[amountField]),...(group==='oneoffs'?[{key:'date',label:'Date',type:'date',min:`${month}-01`,max:`${month}-${new Date(Number(month.slice(0,4)),Number(month.slice(5)),0).getDate()}`}]:[]),...(['fixed','cards','oneoffs'].includes(group)?[{key:'category',label:'Category (optional)',required:false}]:[]),{key:'note',label:'Notes',type:'textarea',required:false},...((repeatable||(!item&&recurring))?[{key:'recurring',label:'Repeat this every month',type:'checkbox'}]:[])];
 edit({title:`${item?'Edit':'Add'} ${GROUPS[group]}`,description:repeatable?'The latest amount carries forward to new months. Turn this off to stop future copies.':recurring?'Monthly amounts are saved for this month. Manage future defaults in Recurring configuration.':undefined,initial:item?{...item,recurring:!!item.sourceId&&user.recurring[group]?.some(r=>r.id===item.sourceId)}:{amount:'',opening:0,closing:'',date:`${month}-01`,recurring},fields},v=>{
  if(group==='remarks'&&!v.text?.trim())throw new Error('Enter a remark.');if(group!=='remarks'&&!v.name?.trim())throw new Error('Enter a name.');
  const sourceId=repeatable&&v.recurring?item?.sourceId||id():undefined,record={...v,id:item?.id||id(),...(sourceId?{sourceId}:{})};delete record.recurring;delete record.estimated;if(repeatable&&!v.recurring)delete record.sourceId;if(group!=='remarks')record.name=v.name.trim();if(group==='accounts'){record.opening=Number(v.opening);record.closing=v.closing===''||v.closing==null?null:Number(v.closing);}else if(group!=='remarks')record.amount=Number(v.amount);
  commit(s=>{let n=updateMonth(s,uid,month,mm=>{mm[group]=item?mm[group].map(r=>r.id===item.id?record:r):[...mm[group],record];mm.completed=mm.completed.filter(x=>x!==({accounts:1,cards:2,fixed:3,investments:4,oneoffs:5,remarks:6}[group]));});if(repeatable){n.users=n.users.map(u=>u.id!==uid?u:{...u,recurring:{...u.recurring,fixed:v.recurring?[...u.recurring.fixed.filter(x=>x.id!==sourceId),{...record,id:sourceId,start:month}]:u.recurring.fixed.filter(x=>x.id!==item?.sourceId)}});}else if(!item&&v.recurring){const template={...record,id:id(),start:month};delete template.opening;delete template.closing;record.sourceId=template.id;n.users=n.users.map(u=>u.id===uid?{...u,recurring:{...u.recurring,[group]:[...u.recurring[group],template]}}:u);}return n;});
 });}
 function copyLastFixed(){const prior=Object.keys(state.months[uid]||{}).filter(key=>key<month).sort().at(-1);if(!prior){setNotice('There is no earlier month to copy.');return;}commit(s=>updateMonth(s,uid,month,mm=>{const existing=new Set(mm.fixed.map(item=>item.sourceId||item.name));for(const item of s.months[uid][prior].fixed){if(!existing.has(item.sourceId||item.name))mm.fixed.push({...item,id:id(),estimated:true});mm.completed=mm.completed.filter(i=>i!==3);}}),'Copied missing fixed expenses from the previous month');}
 function recordList(group){return <Panel title={GROUPS[group]}><div className="list">{m[group].length?m[group].map(r=><div key={r.id}><div><b>{group==='remarks'?r.text:r.name}</b>{r.date&&<small>{r.date}</small>}{r.note&&<small>{r.note}</small>}{group==='accounts'&&<small>Opening {money(r.opening)} · Closing {money(r.closing)}</small>}</div><div className="row-actions">{!['remarks','accounts'].includes(group)&&<strong>{money(r.amount)}</strong>}<button aria-label={`Edit ${r.name||'remark'}`} onClick={()=>editRecord(group,r)}>Edit</button><button className="danger" aria-label={`Delete ${r.name||'remark'}`} onClick={()=>confirmDelete(`Delete ${r.name||'remark'}?`,()=>mutate(mm=>{mm[group]=mm[group].filter(x=>x.id!==r.id);mm.completed=mm.completed.filter(x=>x!==({accounts:1,cards:2,fixed:3,investments:4,oneoffs:5,remarks:6}[group]));},'Deleted'))}>Delete</button></div></div>):<p className="muted">No {GROUPS[group].toLowerCase()} for this month.</p>}</div>{group==='fixed'&&<button onClick={copyLastFixed}>Copy last month</button>}<button className="add" onClick={()=>editRecord(group)}>+ Add {group==='remarks'?'remark':group==='accounts'?'account':'item'}</button></Panel>}
 function configEditor(group,item){edit({title:`${item?'Edit':'Add'} recurring ${GROUPS[group]}`,description:'Defaults apply when a month is first initialized. Existing monthly records are preserved; edit those separately.',initial:item||{start:month,amount:0},fields:[nameField,...(group==='accounts'?[]:[amountField]),{key:'start',label:'First month',type:'month',min:'1900-01',max:'9999-12'},{key:'end',label:'Last month (optional)',type:'month',min:'1900-01',max:'9999-12',required:false}]},v=>{if(!v.name.trim())throw new Error('Enter a name.');if(!validMonth(v.start)||(v.end&&(!validMonth(v.end)||v.end<v.start)))throw new Error('End month must be on or after the first month.');const r={...v,name:v.name.trim(),id:item?.id||id(),...(group!=='accounts'?{amount:Number(v.amount)}:{})};commit(s=>({...s,users:s.users.map(u=>u.id===uid?{...u,recurring:{...u.recurring,[group]:item?u.recurring[group].map(x=>x.id===item.id?r:x):[...u.recurring[group],r]}}:u)}));});}
 function checkinSave(){if(m.step===1&&(!m.accounts.length||m.accounts.some(a=>a.closing===null))){setNotice('Enter a closing balance for every account before continuing.');return;}if(m.step===7&&totals(m).actual===null){setNotice('Enter account closing balances before completing reconciliation.');return;}commit(s=>{const n=ensureMonth(s,uid,month),mm=structuredClone(n.months[uid][month]);mm.completed=[...new Set([...mm.completed,mm.step])];mm.step=Math.min(7,mm.step+1);return {...n,months:{...n.months,[uid]:{...n.months[uid],[month]:mm}}};},m.step===7?'Check-in saved. Any unreconciled difference remains visible.':'Step saved');}
 function reconciliation(){const t=totals(m);return <Panel title={`Reconciliation · ${user.name}`}><div className="reconcileBig"><p>Opening balance <b>{money(t.opening)}</b></p><p>Net cash flow <b>{money(t.remaining)}</b></p><p>Expected closing balance <b>{money(t.expected)}</b></p><p>Actual account balances <b>{money(t.actual)}</b></p><p>Difference <b className={t.difference===0?'good':'red'}>{money(t.difference)}</b></p><div className={t.tallied?'tallied':'not'}>{t.tallied?'✓ Tallied':t.actual===null?'Closing balances needed':t.difference!==0?'Not Tallied': 'Balanced · awaiting review'}</div><p className="muted">Expected = opening + income − expenses − investments. Record missing transactions instead of forcing a match.</p></div></Panel>}
 function exportData(){const url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='PennyFolio-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 const individualPage=!['Dashboard','Trends & Insights','Family','Settings'].includes(page);
 async function signOut(){await request('/api/logout',{method:'POST'});location.reload();}
 return <>{storageError&&<div className="save-error" role="alert"><b>Change not saved.</b> {storageError}<div className="actions"><button onClick={retry}>Retry save</button><button onClick={exportDraft}>Export unsaved draft</button><button onClick={()=>location.reload()}>Discard draft & reload</button></div></div>}<div className="app" inert={busy||!!storageError}><aside><div className="brand"><span aria-hidden="true">P</span> PennyFolio</div><nav aria-label="Main navigation">{NAV.map(n=><button className={page===n?'active':''} key={n} onClick={()=>{setPage(n);setNotice('');}}><PageIcon name={n}/><span>{n}</span></button>)}</nav><label className="mobile-navigation">Go to<select aria-label="Page" value={page} onChange={e=>{setPage(e.target.value);setNotice('');}}>{NAV.map(n=><option key={n}>{n}</option>)}</select></label><div className="user"><b>{user.name}</b><small>{user.email}</small><small>Your private finance space</small></div></aside><main><header><div><h1>{page}</h1><p>{familyView?`${family.name} · Combined family view`:showDashboardData?`${user.name} · Your monthly finances`:'Your personal finance space is ready.'}</p></div><div className="controls">{busy&&<span className="saving-indicator" role="status">Saving…</span>}<div className="seg" aria-label="Dashboard scope"><button className={!familyView?'on':''} onClick={()=>setView('individual')}>Individual</button>{family&&<button className={familyView?'on':''} onClick={()=>setView('family')}>Combined</button>}</div></div></header>
 {(page!=='Dashboard'||showDashboardData)&&<div className="monthbar"><div className="month-nav"><button aria-label="Previous month" disabled={month<='1900-01'} onClick={()=>setMonth(shiftMonth(month,-1))}>‹</button><label><span className="sr-only">Selected month</span><input aria-label="Selected month" type="month" min="1900-01" max="9999-12" value={month} onInput={e=>{if(validMonth(e.target.value))setMonth(e.target.value);}} onChange={e=>{if(validMonth(e.target.value))setMonth(e.target.value);}}/></label><button aria-label="Next month" disabled={month>='9999-12'} onClick={()=>setMonth(shiftMonth(month,1))}>›</button><button onClick={()=>setMonth(currentMonth())}>Today</button></div><small>Available: {monthLabel(range.first,true)} – {monthLabel(range.last,true)} · choose any month or year</small></div>}
 {notice&&<div className="notice" role="status">{notice}<button aria-label="Dismiss notification" onClick={()=>setNotice('')}>×</button></div>}
 {familyView&&individualPage?<Panel title="Family dashboard is an aggregate"><p>Monthly entries belong to each user. Continue as {user.name} to update their finances.</p><button className="primary" onClick={()=>setView('individual')}>Edit {user.name}'s finances</button></Panel>:<>
 {page==='Dashboard'&&!showDashboardData&&<WelcomeDashboard user={user} month={month} start={()=>setPage('Monthly Check-in')} migrate={()=>setPage('Settings')}/>}
 {page==='Dashboard'&&showDashboardData&&<><Metrics now={now} previous={previous}/><div className="grid3"><Panel title="Income vs Expenses"><Trend rows={rows} bars/></Panel><Panel title="Invested and uncommitted trend"><Trend rows={rows}/></Panel><Panel title="This Month"><div className="breakdown"><b>{money(current.regular+current.oneoff)}</b><p>Total spending</p><hr/><p>Regular expenses <strong>{money(current.regular)}</strong></p><p>One-off expenses <strong>{money(current.oneoff)}</strong></p><p>Investments <strong>{money(current.invest)}</strong></p></div></Panel></div><div className="bottom"><Panel title="Monthly check-in"><div className="status"><div className="ring">{current.done}/{ids.length*8}</div><div><b>{familyView?`${ids.length} family members`:user.name}</b><p>Review each section and reconcile your balances.</p><button className="primary" onClick={()=>{setView('individual');setPage('Monthly Check-in');}}>Continue {familyView?user.name+'’s ':''}check-in →</button></div></div></Panel><Panel title="Reconciliation">{!familyView&&<Streak state={state} uid={uid} month={month}/>}<div className="recon"><p>Expected closing balance <b>{money(current.expected)}</b></p><p>Actual closing balance <b>{money(current.actual)}</b></p><p>Difference <b>{money(current.difference)}</b></p><div className={current.tallied?'tallied':'not'}>{current.tallied?'✓ Tallied':'Not Tallied / review incomplete'}</div></div></Panel></div>{familyView&&<div className="section-gap"><Panel title="Family members this month"><div className="list">{family.memberIds.map(mid=>{const u=state.users.find(u=>u.id===mid),t=totals(monthFor(state,mid,month));return <div key={mid}><b>{u.name}</b><span>{money(t.income)} income · {t.done}/8 reviewed · {t.tallied?'Tallied':'Not Tallied'}</span></div>;})}</div></Panel></div>}</>}
 {page==='Monthly Check-in'&&!familyView&&<Streak state={state} uid={uid} month={month}/>}
 {page==='Monthly Check-in'&&<div className="formwrap"><div className="steps">{STEPS.map((s,i)=><button key={s} className={m.step===i?'sel':''} onClick={()=>commit(st=>{const n=ensureMonth(st,uid,month);return {...n,months:{...n.months,[uid]:{...n.months[uid],[month]:{...n.months[uid][month],step:i}}}};},'Step selected')}><span>{m.completed.includes(i)?'✓':i+1}</span>{s}</button>)}</div><div><h2 className="section-title">{monthLabel(month)} · {STEPS[m.step]}</h2>{m.step===0&&<Panel title="Monthly income"><p className="hero-value">{money(m.income)}</p><button className="add" onClick={()=>edit({title:'Edit monthly income',initial:{amount:m.income},fields:[amountField]},v=>mutate(mm=>{mm.income=Number(v.amount);mm.entered=[...new Set([...(mm.entered||[]),'income'])];mm.completed=mm.completed.filter(i=>i!==0);}))}>Edit income</button></Panel>}{m.step>0&&m.step<7&&recordList(['','accounts','cards','fixed','investments','oneoffs','remarks'][m.step])}{m.step===7&&reconciliation()}<div className="actions section-gap"><button disabled={m.step===0} onClick={()=>commit(s=>{const n=ensureMonth(s,uid,month);return {...n,months:{...n.months,[uid]:{...n.months[uid],[month]:{...n.months[uid][month],step:m.step-1}}}};},'Previous step')}>← Back</button><button className="primary" onClick={checkinSave}>{m.step===7?'Save reconciliation':'Save & continue →'}</button></div></div></div>}
 {page==='Expenses & Investments'&&<><h2 className="section-title">This month’s entries</h2><div className="grid2">{['accounts','cards','fixed','investments','oneoffs','remarks'].map(g=><React.Fragment key={g}>{recordList(g)}</React.Fragment>)}</div><h2 className="section-title">Recurring configuration</h2><p className="muted">Defaults for newly opened months. Existing months keep their own entries and amounts. Account balances start blank each month.</p><div className="grid2">{Object.keys(user.recurring).map(g=><Panel key={g} title={GROUPS[g]}><div className="list">{user.recurring[g].map(r=><div key={r.id}><div><b>{r.name}</b><small>{r.amount!==undefined&&`${money(r.amount)} · `}{r.start} → {r.end||'ongoing'}</small></div><div className="row-actions"><button onClick={()=>configEditor(g,r)}>Edit</button><button className="danger" onClick={()=>confirmDelete(`Delete recurring ${r.name}?`,()=>commit(s=>({...s,users:s.users.map(u=>u.id===uid?{...u,recurring:{...u.recurring,[g]:u.recurring[g].filter(x=>x.id!==r.id)}}:u)})),'Stops this default from appearing in newly initialized months. Existing monthly entries are kept.')}>Delete</button></div></div>)}</div><button className="add" onClick={()=>configEditor(g)}>+ Add recurring item</button></Panel>)}</div></>}
 
 {page==='Reconciliation'&&<div className="grid2"><div>{reconciliation()}<button className="primary section-gap" onClick={()=>{if(totals(m).actual===null){setNotice('Enter account closing balances first.');return;}commit(s=>{const n=ensureMonth(s,uid,month);const mm=n.months[uid][month];return {...n,months:{...n.months,[uid]:{...n.months[uid],[month]:{...mm,completed:[...new Set([...mm.completed,7])]}}}};},'Reconciliation reviewed');}}>Save reconciliation review</button></div>{recordList('accounts')}</div>}
 {page==='Trends & Insights'&&<><div className="grid2"><Panel title="Invested and uncommitted trend"><Trend rows={rows}/></Panel><Panel title="Cash flow"><Trend rows={rows} bars/></Panel></div><Panel title="Monthly detail"><Detail rows={rows}/></Panel></>}
 {page==='Family'&&<div className="grid2"><Panel title={family?family.name:'Your family'}>{family?<><p className="muted">Members share their finance history in the Combined dashboard. Each member edits only their own records.</p><div className="list">{family.memberIds.map(mid=>{const u=state.users.find(u=>u.id===mid);return <div key={mid}><div><b>{u.name}{mid===uid?' (you)':''}</b><small>{u.email}</small></div><span className="badge">Member</span></div>;})}</div><div className="actions section-gap"><button className="primary" onClick={()=>{setView('family');setPage('Dashboard');}}>Open Combined dashboard</button><button onClick={()=>edit({title:'Invite a family member',description:'The invitation works only for this verified Google email and expires in seven days. Share the code directly with the intended person.',fields:[{key:'email',label:'Google email address',type:'email'}]},async v=>{setInvitation(await familyAction('/api/families/invites',{email:v.email}));})}>Invite member</button><button className="danger" onClick={()=>edit({title:'Leave family?',description:'Your personal finances are kept. Family members will no longer have access to your records.',fields:[],saveLabel:'Leave family'},async()=>{await familyAction('/api/families/leave');setView('individual');setInvitation(null);})}>Leave family</button></div>{invitation&&<div className="invite-result"><p>Invitation for <b>{invitation.email}</b></p><code>{invitation.code}</code><p>Expires {new Date(invitation.expiresAt).toLocaleString()}. This code is shown only now.</p></div>}</>:<><p>Create a family or accept an invitation sent to your Google email.</p><div className="actions"><button className="primary" onClick={()=>edit({title:'Create family',fields:[nameField]},v=>familyAction('/api/families',{name:v.name}))}>Create family</button><button onClick={()=>edit({title:'Join family',description:'Joining shares your finance history with the family and lets you view theirs. You keep control of your own entries.',fields:[{key:'code',label:'Invitation code'}],saveLabel:'Join and share finances'},async v=>{await familyAction('/api/families/join',{code:v.code});setView('family');})}>Join family</button></div></>}</Panel><Panel title="Separate accounts, shared family"><p>Each person signs in with their own Google account. Invite as many family members as you need.</p><p className="muted">Invitations are single-use, expire after seven days, and are tied to the invited email. The server checks membership on every request.</p></Panel></div>}
 {page==='Budget Goals'&&!familyView&&<Budget key={uid+page} user={user} record={m} onSave={async budget=>{const ok=await commit(s=>({...s,users:s.users.map(u=>u.id===uid?{...u,budget}:u)}),'Budget goals saved');if(!ok)throw new Error('Budget was not saved. Recover the save above.');}}/>}
 {page==='Settings'&&<Settings user={user} edit={edit} commit={commit} exportData={exportData} confirmDelete={confirmDelete} importLegacy={payload=>familyAction('/api/import/legacy',payload)} signOut={signOut}/>}
 </>}{editor&&<Editor key={editor.title} spec={editor} onClose={()=>setEditor(null)} onSave={async v=>{await editor.save(v);setEditor(null);}}/>}<footer>PennyFolio · {familyView?'Family totals':user.name} · Saved to your server</footer></main></div></>;
}
function WelcomeDashboard({user,month,start,migrate}){return <section className="welcome-dashboard"><div className="welcome-hero"><div><p className="eyebrow">WELCOME, {user.name.split(' ')[0].toUpperCase()}</p><h2>Start with the money you already track.</h2><p>Your dashboard will come alive as soon as you bring in your history or complete your first monthly check-in.</p></div><div className="welcome-mark">₹</div></div><div className="onboarding-options"><button onClick={migrate}><b>Import existing history</b><span>Bring in your past months from a finance workbook.</span><i>→</i></button><button onClick={start}><b>Start {monthLabel(month)}</b><span>Add income, accounts, expenses and investments.</span><i>→</i></button></div><Panel title="A calm first check-in"><div className="onboarding-steps"><span><b>1</b>Add income and account balances</span><span><b>2</b>Review expenses and investments</span><span><b>3</b>Reconcile when you are ready</span></div></Panel></section>}
function Settings({user,edit,commit,exportData,confirmDelete,importLegacy,signOut}){
 function update(fn){return commit(s=>({...s,users:s.users.map(u=>u.id===user.id?fn(u):u)}));}
 function schedule(r){edit({title:r?'Edit reminder':'Add reminder',initial:r||{day:25,time:'19:00',purpose:'Follow-up if incomplete',enabled:true},fields:[{key:'day',label:'Day of month',type:'number',min:1,max:31,step:1},{key:'time',label:'Time',type:'time'},{key:'purpose',label:'Purpose',type:'select',options:['Start monthly check-in','Follow-up if incomplete','Final reconciliation']},{key:'enabled',label:'Enabled',type:'checkbox'}]},v=>update(u=>({...u,reminders:{...u.reminders,schedules:r?u.reminders.schedules.map(x=>x.id===r.id?{...v,id:r.id,day:Number(v.day)}:x):[...u.reminders.schedules,{...v,id:id(),day:Number(v.day)}]}})));}
 function legacyImport(){edit({title:'Import an Excel workbook',description:'Choose a tracker .xlsx file and enter the worksheet to import. The worksheet is read in this browser; only the converted finance data is sent to your server. Your Google identity and reminder preferences are kept.',initial:{worksheetName:'',file:null,confirmed:false},fields:[{key:'worksheetName',label:'Worksheet name'},{key:'file',label:'Excel workbook (.xlsx)',type:'file',accept:'.xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'},{key:'confirmed',label:'I understand this imports financial data into my signed-in account',type:'checkbox'}]},async v=>{const source=await parseLegacyWorkbook(v.file,v.worksheetName);await importLegacy({profileName:source.users[0].name,source,confirmed:v.confirmed});});}
 return <div className="grid2"><Panel title={`User profile · ${user.name}`}><p><b>{user.name}</b></p><p>{user.email}</p><p>Timezone: {user.timezone}</p><button className="add" onClick={()=>edit({title:'Edit user profile',initial:user,fields:[nameField,{key:'timezone',label:'IANA timezone (e.g. Asia/Kolkata)'}]},v=>{if(!v.name.trim())throw new Error('Enter a name.');try{new Intl.DateTimeFormat('en',{timeZone:v.timezone});}catch{throw new Error('Enter a valid timezone, such as Asia/Kolkata or UTC.');}return update(u=>({...u,name:v.name.trim(),timezone:v.timezone}));})}>Edit profile</button><hr/><p className="muted">Export your accessible finance data and family records as JSON.</p><button onClick={exportData}>Export backup</button><hr/><h3>Import from Excel</h3><p className="muted">Use this once, before adding server records. Choose a workbook and its worksheet. It never overwrites existing monthly data.</p><button className="add" onClick={legacyImport}>Choose Excel workbook</button><hr/><button className="quiet-action" onClick={signOut}>Sign out of this account</button></Panel><Panel title="Email reminder preferences"><p className="muted">Saved for {user.name}. Reminders use your Google email and timezone. Delivery requires the server scheduler and SMTP to be enabled. Days beyond a month’s length run on its last day.</p><div className="checks">{[['enabled','Enable reminders'],['onlyIfIncomplete','Only if check-in is incomplete'],['stopWhenTallied','Stop once tallied'],['includeMissing','Include missing items in email']].map(([key,label])=><label key={key}><input type="checkbox" checked={user.reminders[key]} onChange={e=>update(u=>({...u,reminders:{...u.reminders,[key]:e.target.checked}}))}/>{label}</label>)}</div><div className="list section-gap">{user.reminders.schedules.map(r=><div key={r.id}><div><b>Day {r.day} · {r.time}</b><small>{r.purpose} · {r.enabled?'Enabled':'Disabled'}</small></div><div className="row-actions"><button onClick={()=>schedule(r)}>Edit</button><button className="danger" onClick={()=>confirmDelete('Delete reminder?',()=>update(u=>({...u,reminders:{...u.reminders,schedules:u.reminders.schedules.filter(x=>x.id!==r.id)}})),'Remove this reminder from your personal schedule.')}>Delete</button></div></div>)}</div><button className="add" onClick={()=>schedule()}>+ Add reminder</button></Panel></div>}
function ServerApp(){
 const [initial,setInitial]=useState(null),[error,setError]=useState(''),[signedOut,setSignedOut]=useState(false),[config,setConfig]=useState(null);
 useEffect(()=>{request('/api/config').then(setConfig).catch(()=>{});request('/api/state').then(setInitial).catch(e=>{if(e.status===401)setSignedOut(true);else setError(e.message);});},[]);
 if(initial)return <App initialState={initial}/>;
 return <main className="auth-page"><section className="auth-wrap"><div className="auth-copy"><div className="auth-brand"><span aria-hidden="true">P</span> PennyFolio</div><p className="eyebrow">A CLEARER MONTH, EVERY MONTH</p><h1>From everyday spending to bigger plans.</h1><p>Track your own finances, then share a family view with the people you trust.</p><div className="auth-points"><span>Personal monthly check-ins</span><span>Private accounts and reminders</span><span>Family totals when you choose</span></div></div><section className="auth-card"><div className="login-brand" aria-hidden="true">P</div><p className="eyebrow">WELCOME</p><h2>Let’s get started.</h2><p>Use your Google account to open your private finance space.</p>{signedOut?<>{config?.googleConfigured?<a className="primary google-login" href="/oauth2/authorization/google">Continue with Google <span>→</span></a>:<button className="primary google-login" disabled>Configure Google sign-in</button>}{config&&!config.googleConfigured&&<p className="error">Google sign-in is not configured yet. Add your OAuth client ID and secret on the server, then try again.</p>}<p className="auth-note">Each person signs in with their own Google account. You choose when to share a family dashboard.</p></>:error?<p role="alert" className="error">{error} <button onClick={()=>location.reload()}>Retry</button></p>:<p role="status" className="auth-loading">Opening your finance space…</p>}{new URLSearchParams(location.search).has('login')&&<p className="error">Google sign-in did not complete. Check the server OAuth configuration and try again.</p>}</section></section></main>;
}
createRoot(document.getElementById('root')).render(<ServerApp/>);
